Areas/Admin/Controllers/DepartmentAEDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminWeb.Models;

namespace AdminWeb.Areas.Admin.Controllers
{
    public class DepartmentAEDController : Controller
    {
        #region Add Departments
        private ManageDEP md = new ManageDEP();
        public ActionResult AddDepartments()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDepartments(FormCollection fc)
        {
            Departmenttbl dep = new Departmenttbl();
            dep.DID = Convert.ToInt32(fc["hdnID"]);
            dep.DName_ = fc["depname"];
            dep.DHOD = fc["dephod"];
           int op = md.AddEditDeleteDepartment(dep, 1);

            if (op > 0)
            {
                    ViewBag.msg = "Data Saved";
            }
            else
            {
                ViewBag.msg = "Try Again";
            }


            return View();
        }
        #endregion

        #region View All Departments
        public ActionResult ViewDEP()
        {
            return View(md.GetDepartments());
        }
        #endregion

        #region Edit Departments
        public ActionResult EditDepartments(int id)
        {
            var department = md.GetDepartmentbyID(id);

            return View(department);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDepartments(FormCollection fc, int id)
        {
            Departmenttbl dep = new Departmenttbl();
            dep.DID = Convert.ToInt32(fc["hdnID"]);
            dep.DName_ = fc["depname"];
            dep.DHOD = fc["dephod"];
            int op = md.AddEditDeleteDepartment(dep, 2);

            if (op > 0)
            {
               TempData["msg"] = "Data Updated";
                return RedirectToAction("ViewDEP");
            }
            else
            {
                TempData["msg"] = "Try Again";
                return View();
            }

        }
        #endregion

        #region Delete Departments
        public ActionResult DeleteDeparetments(int id)
        {
            var department = md.GetDepartmentbyID(id);
            if (department!=null)
            {
                int op = md.AddEditDeleteDepartment(department, 3);
                if (op > 0)
                {
                    TempData["msg"] = "Data Deleted";
                    return RedirectToAction("ViewDEP");
                }
                else
                {
                    TempData["msg"] = "Try Again";
                    return View();
                }
            }
            return View();
        }
        #endregion
    }
}

Areas/Admin/Views/DepartmentAED/AddDepartments.cshtml
@{
    ViewBag.Title = "AddDepartments";
}

<h2>AddDepartments</h2>
@ViewBag.msg
@using (Html.BeginForm("AddDepartments", "DepartmentAED", FormMethod.Post))
{

    @Html.AntiForgeryToken();

    <input type="hidden" name="hdnID" value="0" />
    <div class="form-group">
        <label for="email">Department Name</label>
        <input type="text" class="form-control" id="depname" name="depname">
    </div>
    <div class="form-group">
        <label for="pwd">DEpartments HOD</label>
        <input type="text" class="form-control" id="dephod" name="dephod">
    </div>
    <button type="submit" class="btn btn-success">Submit</button>
    <button type="reset" class="btn btn-danger">Cancel</button>
}

Areas/Admin/Views/DepartmentAED/EditDepartments.cshtml
@using AdminWeb.Models;
@{
    ViewBag.Title = "EditDepartments";
    Departmenttbl dp = Model;
}

<h2>EditDepartments</h2>
@TempData["msg"]
@using (Html.BeginForm("EditDepartments", "DepartmentAED", FormMethod.Post))
{

    @Html.AntiForgeryToken();

    <input type="hidden" name="hdnID" value="@dp.DID" />
    <div class="form-group">
        <label for="email">Department Name</label>
        <input type="text" class="form-control" value="@dp.DName_" id="depname" name="depname">
    </div>
    <div class="form-group">
        <label for="pwd">DEpartments HOD</label>
        <input type="text" class="form-control" value="@dp.DHOD" id="dephod" name="dephod">
    </div>
    <button type="submit" class="btn btn-success">Update</button>
    <button type="reset" class="btn btn-danger">Cancel</button>
}

Areas/Admin/Views/DepartmentAED/ViewDEP.cshtml
@using AdminWeb.Models;
@{
    ViewBag.Title = "ViewDEP";
    List<Departmenttbl> li = Model;
}

<h2>ViewDEP</h2>


<table class="table table-responsive">
    <thead>
        <tr>
            <th>Department ID</th>
            <th>Department Name</th>
            <th>Department HOD</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in li)
        {
            <tr>
                
                <td>@item.DID</td>
                <td>@item.DName_</td>
                <td>@item.DHOD</td>
                <td>
                    <a href="EditDepartments/@item.DID" class="btn-link" >Edit</a> | 
                    <a href="DeleteDeparetments/@item.DID"  onclick="return confirm('Are you sure want to Delete')" class="btn-link">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>